### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by YiChenCityU** [willSapgreen/stereo-vision#2]

**Comment by willSapgreen** [comment]
@YiChenCityU ,
can you specify
1. error
2. the system you are using
Thank you.

**Comment by buaa1989** [comment]
HI, I met some errors when I built the project.

1 errors:
/home/ry/3D/stereo-vision/stereomapperbak/framecapturethread.cpp:102: error: ‘class CalibIOKITTI’ has no member named ‘height’
         Mx = cvCreateMat(calib->height(),calib->width(),CV_32F);
                                 ^
/home/ry/3D/stereo-vision/stereomapperbak/framecapturethread.cpp:102: error: ‘class CalibIOKITTI’ has no member named ‘width’
         Mx = cvCreateMat(calib->height(),calib->width(),CV_32F);
                                                 ^
/home/ry/3D/stereo-vision/stereomapperbak/framecapturethread.cpp:109: error: ‘class CalibIOKITTI’ has no member named ‘K1’
             cv::Mat tmpK1 = cv::cvarrToMat( calib->K1 );
                                                    ^
....

2 ubuntu 16.4 QT4.8

Thanks

**Comment by willSapgreen** [comment]
Hello @buaa1989 
cvCreateMat and cvarrToMat are the functions in OpenCV.
Please make sure you have OpenCV installed and link it properly.
